// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCR5K4Bfxibor2CQi4MybEFUv1jPv4HQAo',
    appId: '1:372368420410:web:d001c578e3f805a5190f03',
    messagingSenderId: '372368420410',
    projectId: 'uoemapp',
    authDomain: 'uoemapp.firebaseapp.com',
    storageBucket: 'uoemapp.appspot.com',
    measurementId: 'G-CWVS118B3M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjsbNiYwQUkoPDf45U_S_FlNnTltjBv5I',
    appId: '1:372368420410:android:9bd682c7b68ee889190f03',
    messagingSenderId: '372368420410',
    projectId: 'uoemapp',
    storageBucket: 'uoemapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpYQjvzD56Zcn1Q_v5ea3N723stf9RMLk',
    appId: '1:372368420410:ios:c5271da05e4cdd99190f03',
    messagingSenderId: '372368420410',
    projectId: 'uoemapp',
    storageBucket: 'uoemapp.appspot.com',
    iosBundleId: 'com.lxmwaniky.flutterFirebaseAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpYQjvzD56Zcn1Q_v5ea3N723stf9RMLk',
    appId: '1:372368420410:ios:57a11383ddde96d0190f03',
    messagingSenderId: '372368420410',
    projectId: 'uoemapp',
    storageBucket: 'uoemapp.appspot.com',
    iosBundleId: 'com.lxmwaniky.flutterFirebaseAuth.RunnerTests',
  );
}
