// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show Firebase, FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
import 'firebase_options.dart';
/// // ...
Future<void> initializeFirebase() async {
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
}
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmw6QUafxajnUHJBsF5npRk3CqoSRMEIQ',
    appId: '1:452909170188:web:0516cd38642d64c2697829',
    messagingSenderId: '452909170188',
    projectId: 'fir-test-38783',
    authDomain: 'fir-test-38783.firebaseapp.com',
    storageBucket: 'fir-test-38783.appspot.com',
    measurementId: 'G-RPHSSV360V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGyxTA3NOPTjcmNWmXyOEU7IS4_oAXbKI',
    appId: '1:452909170188:android:31ffc9c70d829961697829',
    messagingSenderId: '452909170188',
    projectId: 'fir-test-38783',
    storageBucket: 'fir-test-38783.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMcxUamHK3qjcL6eLlT5yvX3HOVsSJww8',
    appId: '1:452909170188:ios:5dad5ca27a1ffdb2697829',
    messagingSenderId: '452909170188',
    projectId: 'fir-test-38783',
    storageBucket: 'fir-test-38783.appspot.com',
    iosBundleId: 'com.lxmwaniky.flutterFirebaseAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMcxUamHK3qjcL6eLlT5yvX3HOVsSJww8',
    appId: '1:452909170188:ios:44095d232d73e671697829',
    messagingSenderId: '452909170188',
    projectId: 'fir-test-38783',
    storageBucket: 'fir-test-38783.appspot.com',
    iosBundleId: 'com.lxmwaniky.flutterFirebaseAuth.RunnerTests',
  );
}
